export class CtmUserModel {
    ctmId: number = 0
    ctmUser: string = ""
    ctmPassword: string = ""
    ctmTitle: string = ""
    ctmFirstname: string = ""
    ctmLastname: string = ""
    ctmGender: string = ""
    ctmBirth: string = ""
    ctmPhon: string = ""
    ctmEmail: string = ""
    ctmAddrss: string = ""
    ctmUniversity: string = ""
    ctmFaculty: string = ""
    ctmMajor: string = ""
    ctmWeight: string = ""
    ctmHeight: string = ""
    ctmStatus: string = ""
    zipCode: string = ""
    roleId: number = 0
}